### ISSUE TITLE
ido information still pointed to google project

### ISSUE THREAD

**Issue by zhengj2007** [infectious-disease-ontology/infectious-disease-ontology#47]
The IDO information has not updated. All OWL files still point to google project. Is it possible to update the link on following website:
http://www.obofoundry.org/ontology/ido.html
http://www.ontobee.org/ontology/IDO

I have problem to view the IDO using the following link today:
http://infectious-disease-ontology.googlecode.com/svn/releases/2014-08-01/ido.owl

**Comment by zhengj2007** [comment]
Can it be fixed soon? 

We cannot load the IDO from the link:
http://purl.obolibrary.org/obo/ido.owl which redirect to:
http://infectious-disease-ontology.googlecode.com/svn/releases/2014-08-01/ido.owl
since the google code shut down.

**Comment by lgcowell** [comment]
I don’t seem to have edit privileges on the obofoundry site.  I will reach out to Chris to see how to proceed.  I will reach out to Oliver for ontobee.

The appropriate URL is https://github.com/lgcowell/infectious-disease-ontology.

Thank you for letting us know.

Lindsay
— ——————————————
Lindsay G. Cowell, PhD
Associate Professor
Division of Biomedical Informatics
Department of Clinical Sciences
University of Texas Southwestern Medical Center
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>
214-648-2289

Administrative Assistant:
Mack Dressler
Mack.Dressler@UTSouthwestern.edu<mailto:Mack.Dressler@UTSouthwestern.edu>
214-648-2558

**Comment by zhengj2007** [comment]
@lgcowell you can do it when you have a github account. You can make the changes and commit it in your own branch and create a pull request for your commit.
The file you need to update is:
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/ido.yml

**Comment by zhengj2007** [comment]
@lgcowell I can help on update the IDO purl redirects and IDO project metadata on the OBO Foundry website. However, I cannot find the release files in the IDO github project. Could you please let me know the links of them? So, I can set the PURL redirects. The EuPathDB project is using IDO and need to load it into the database. It would be nice the issue can be fixed ASAP.

**Comment by zhengj2007** [comment]
@lgcowell I downloaded IDO source code from google project and added into my own account today. There is a directory, releases, contains IDO release files. However, I cannot find these files in the IDO github. 
https://github.com/zhengj2007/infectious-disease-ontology

**Comment by lgcowell** [comment]
Hi Jie,

Thank you for offering to help.  I really appreciate it.  It looks like not all the files/directories migrated from Google Code.

I checked in some new files, but I still need to make sure all the newest stuff is in there.  I am on my third harddrive since the migration and want to make sure I am looking at the most current local repository.  I will let you know when I am sure all the most recent release files are in.

Thanks!

— ——————————————
Lindsay G. Cowell, PhD
Associate Professor
Division of Biomedical Informatics
Department of Clinical Sciences
University of Texas Southwestern Medical Center
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>
214-648-2289

Administrative Assistant:
Mack Dressler
Mack.Dressler@UTSouthwestern.edu<mailto:Mack.Dressler@UTSouthwestern.edu>
214-648-2558

**Comment by lgcowell** [comment]
Yes, it looks like some directories are missing after the google code migration.  Trying to fix that now …

— ——————————————
Lindsay G. Cowell, PhD
Associate Professor
Division of Biomedical Informatics
Department of Clinical Sciences
University of Texas Southwestern Medical Center
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>
214-648-2289

Administrative Assistant:
Mack Dressler
Mack.Dressler@UTSouthwestern.edu<mailto:Mack.Dressler@UTSouthwestern.edu>
214-648-2558

**Comment by lgcowell** [comment]
The files you need should be in https://github.com/lgcowell/infectious-disease-ontology/tree/master/releases/2014-08-01

I am going to try and update the ido.yml etc now.

Thanks,

Lindsay

— ——————————————
Lindsay G. Cowell, PhD
Associate Professor
Division of Biomedical Informatics
Department of Clinical Sciences
University of Texas Southwestern Medical Center
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>
214-648-2289

Administrative Assistant:
Mack Dressler
Mack.Dressler@UTSouthwestern.edu<mailto:Mack.Dressler@UTSouthwestern.edu>
214-648-2558

**Comment by zhengj2007** [comment]
@lgcowell Thanks for your quick response. Please let me know if anything I can help.

**Comment by lgcowell** [comment]
Might you have time for a short phone call this afternoon?

Thanks!

Sent from my iPhone

On Jun 23, 2016, at 8:40 PM, jie zheng <notifications@github.com<mailto:notifications@github.com>> wrote:


@lgcowell<https://github.com/lgcowell> Thanks for your quick response. Please let me know if anything I can help.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/lgcowell/infectious-disease-ontology/issues/47#issuecomment-228234863>, or mute the thread<https://github.com/notifications/unsubscribe/AF4uhZz4WEch6gLOZ-wvaVEvBqVCiEBIks5qOzWdgaJpZM4IcfgJ>.

________________________________

UT Southwestern


Medical Center



The future of medicine, today.

**Comment by zhengj2007** [comment]
@lgcowell 

I made following changes on IDO development version:
- cleaned up xml namespace
- removed invalid ontology import link
- update relations from OBO-REL (deprecated) to latest RO ones, current using RO core relations and manually import relations in ido-external-by-hand.owl. The relation mappings are recorded in the file: /trunk/src/ontology/ido-core/mapping.txt

Following changes on release 2010-12-02
- ontology-metadata.owl linked to current release compatible version
- made a merged release file

Following changes on release 2014-08-01
- ontology-metadata.owl using a version IRI
- updated import link not using google project links but ontology IRI
- removed invalid import ontology links
- made a merged release file

I think PURL redirect to a merged release file is much easy to maintain especially when location of the project repository is changed.

The editing commit history can be found on the page:
https://github.com/infectious-disease-ontology/infectious-disease-ontology/commits/jz

Lindsay, could you please review the development version IDO under jz branch:
https://github.com/infectious-disease-ontology/infectious-disease-ontology/tree/jz/trunk/src/ontology/ido-core

If you think it is OK, I will merge the changes I made to master branch and make a new release.

Thanks!

Jie

ps: I have updated IDO PURL links by editing ido.yml. James has committed the changes I made. However, it won't fix the issue of loading latest IDO release (2014-08-01) since the PURLs were not set for the imported IDO files.

**Comment by lgcowell** [comment]
These look great!  Thank you!!



— ——————————————
Lindsay G. Cowell, PhD
Associate Professor
Division of Biomedical Informatics
Department of Clinical Sciences
University of Texas Southwestern Medical Center
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>
214-648-2289

Administrative Assistant:
Mack Dressler
Mack.Dressler@UTSouthwestern.edu<mailto:Mack.Dressler@UTSouthwestern.edu>
214-648-2558

**Comment by zhengj2007** [comment]
@lgcowell Shall i merge the changes and make a release of IDO?

**Comment by lgcowell** [comment]
That would be wonderful!  Thank you again for all your help!

Sent from my iPhone

On Jul 3, 2016, at 10:21 PM, jie zheng <notifications@github.com<mailto:notifications@github.com>> wrote:


@lgcowell<https://github.com/lgcowell> Shall i merge the changes and make a release of IDO?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/infectious-disease-ontology/infectious-disease-ontology/issues/47#issuecomment-230192509>, or mute the thread<https://github.com/notifications/unsubscribe/AF4uhSJHdooaGSSBIm5_fWoJniiMDpLpks5qSG4SgaJpZM4IcfgJ>.

________________________________

UT Southwestern


Medical Center



The future of medicine, today.

**Comment by zhengj2007** [comment]
Sure. I will work on it.
Jie

**Comment by zhengj2007** [comment]
@lgcowell I have created a new release and merged the changes I made to master branch. I will update the PURLs redirection. When everything works, I will let you know.

**Comment by lgcowell** [comment]
That's fantastic.  Thanks!

Sent from my iPhone

On Jul 5, 2016, at 1:47 PM, jie zheng <notifications@github.com<mailto:notifications@github.com>> wrote:

@lgcowellhttps://github.com/lgcowell I have created a new release and merged the changes I made to master branch. I will update the PURLs redirection. When everything works, I will let you know.

## 

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHubhttps://github.com/infectious-disease-ontology/infectious-disease-ontology/issues/47#issuecomment-230550579, or mute the threadhttps://github.com/notifications/unsubscribe/AF4uhV1Y36HTuJy7zt1qaCsABJ4Vxzz9ks5qSpjCgaJpZM4IcfgJ.

---

UT Southwestern

Medical Center

The future of medicine, today.

**Comment by zhengj2007** [comment]
@lgcowell IDO purls have been updated. We are done :)

**Comment by lgcowell** [comment]
Yay!!

Sent from my iPhone

On Jul 6, 2016, at 10:15 PM, jie zheng <notifications@github.com<mailto:notifications@github.com>> wrote:

@lgcowellhttps://github.com/lgcowell IDO purls have been updated. We are done :)

## 

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHubhttps://github.com/infectious-disease-ontology/infectious-disease-ontology/issues/47#issuecomment-230961286, or mute the threadhttps://github.com/notifications/unsubscribe/AF4uhUWMer3Yugkka1fZz27wcO-dxBu4ks5qTGE3gaJpZM4IcfgJ.

---

UT Southwestern

Medical Center

The future of medicine, today.
